---
name: POE-Component-IRC-Plugin-WWW-Cache-Google
version: 0.0101
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: give URIs to Google's cache pages checking if they exist
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.003
  POE::Component::WWW::Cache::Google: 0.0201
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::WWW::Cache::Google:
    file: lib/POE/Component/IRC/Plugin/WWW/Cache/Google.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
